//////// Create a frequency 
###
POST http://localhost:4000/frequencies HTTP/1.1
content-Type: application/json

{
    "description": "Daily"
}

///////////////// Get all frequency
###
GET http://localhost:4000/frequencies HTTP/1.1

