/// Get all Loans
###
GET http://localhost:4000/loans HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYzMDE4Mzg5LCJleHAiOjE2NjM2MjMxODl9.2Y5dtL7WAhNEFrgFH9I84ptWTr2l3TcdEA6YxeGMYeE


/// Get Loan by ID
###
GET http://localhost:4000/loans/631ff9dfd702321448fb96d7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYzMDE4Mzg5LCJleHAiOjE2NjM2MjMxODl9.2Y5dtL7WAhNEFrgFH9I84ptWTr2l3TcdEA6YxeGMYeE

/// Create a new loan
### 
POST http://localhost:4000/loans HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYzMDE4Mzg5LCJleHAiOjE2NjM2MjMxODl9.2Y5dtL7WAhNEFrgFH9I84ptWTr2l3TcdEA6YxeGMYeE

{
 "customer_id": "631e893ab00295f8f492a2ed",
 "date": "2022-09-16",
 "amount": 150000,
 "interest": 0.15,
 "term": 12,
 "firstday_payment": "2022-09-22",
 "status_aproval": false,
 "frequency_payment": "631ec1c692cebf552c555b8e",
 "types_payment": "631ebd0cb114e841d3d7937d",
 "user_id": "631c2a249280df1998339e73"
}

////////////////////////////////
###
// Update a loan when exists 
PUT http://localhost:4000/loans/631fef221cab33a59239bef9 HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYzMDI5ODg4LCJleHAiOjE2NjM2MzQ2ODh9.qDeZ6LYiA5X7ulqIo6FEsCtk0CA-g1h7RQ7wiCTBTww

{
  "customer_id": "631e893ab00295f8f492a2ed",
  "date": "2022-09-18",
  "amount": 130000,
  "interest": 0.18,
  "term": 18,
  "firstday_payment": "2022-09-22",
  "status_aproval": false,
  "frequency_payment": "631ec1c692cebf552c555b8e",
  "types_payment": "631ebd0cb114e841d3d7937d" 
} 

/////////////////////////////
// Delete a customer
###
DELETE http://localhost:4000/loans/631fef221cab33a59239bef9 HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYzMDE4Mzg5LCJleHAiOjE2NjM2MjMxODl9.2Y5dtL7WAhNEFrgFH9I84ptWTr2l3TcdEA6YxeGMYeE

/////////////////////////////
// Delete All customer
###
DELETE http://localhost:4000/loans HTTP/1.1
content-Type: application/json
////////////////////////////