///////////////// Get all Loans
###
GET http://localhost:4000/loans HTTP/1.1

///////////////////
/// Get Loan by ID
###
GET http://localhost:4000/loans/631e893ab00295f8f492a2ed HTTP/1.1


//////
###
// Create a new loan 
POST http://localhost:4000/loans HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYyOTM5MTQwLCJleHAiOjE2NjM1NDM5NDB9.b0UlIMhpkjRU0itZDijhQzocNlBHEvOvUQyANBTo5dU

{
  "sin": "545456189",
  "first_name": "John",
  "last_name": "Doe",
  "phone_number": "123-456-7890",
  "email": "john5@gmail.com",
  "birth_date": "1990-01-01",
  "salary_month": 1000.00,
  "address":{ 
    "address1": "123 Main St",
    "address2": "",
    "city_id": "631e37846af11738e767c672",
    "postal_code": "M1M1M1"
   },
  "picture_url": "https://www.google.com",
  "status_migration_id": "631e8706ce615f2089df58ac",
  "bank_account": "123456789",
  "bank_route": "123456789",
  "bank_branch": "123"
} 


////////////////////////////////
###
// Update a loan when exists 
PUT http://localhost:4000/loans/631e893ab00295f8f492a2ed HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYyOTM5MTQwLCJleHAiOjE2NjM1NDM5NDB9.b0UlIMhpkjRU0itZDijhQzocNlBHEvOvUQyANBTo5dU

{
  "sin": "545456325",
  "first_name": "Hammid",
  "last_name": "Ariel",
  "phone_number": "123-258-3096",
  "email": "xxx43@gmail.com",
  "birth_date": "1990-01-01",
  "salary_month": 5000.00,
  "address":{ 
    "address1": "30 San RomanoWay",
    "address2": "",
    "city_id": "631e37846af11738e767c672",
    "postal_code": "M1M1M1"
   },
  "picture_url": "https://www.google.com",
  "status": false,
  "bank_account": "987654321",
  "bank_route": "987654321",
  "bank_branch": "321"
} 


/////////////////////////////
// Delete a customer
###
DELETE http://localhost:4000/loans/631d5d1a9825aa6653fe22c5 HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYyOTM5MTQwLCJleHAiOjE2NjM1NDM5NDB9.b0UlIMhpkjRU0itZDijhQzocNlBHEvOvUQyANBTo5dU


/////////////////////////////
// Delete All customer
###
DELETE http://localhost:4000/loans HTTP/1.1
content-Type: application/json
////////////////////////////