//////// Create a Typesopayment
###
POST http://localhost:4000/typespayments HTTP/1.1
content-Type: application/json

{
    "description": "Student",
    "interest_rate": 0.125
}

///////////////// Get all Typespayment
###
GET http://localhost:4000/typespayments HTTP/1.1

