//////// Create a user
###
POST http://localhost:4000/users HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMWMyYTI0OTI4MGRmMTk5ODMzOWU3MyIsInVzZXJuYW1lIjoiZ3VpbGxlcm1vIiwiaWF0IjoxNjYyOTM5MTQwLCJleHAiOjE2NjM1NDM5NDB9.b0UlIMhpkjRU0itZDijhQzocNlBHEvOvUQyANBTo5dU

{
    "username": "test",
    "name": "test name",
    "password": "1234",
    "email": "test@gmail.com",
    "phone_number": "1234567890",
    "role": "631c11541c167f23eda656bb"
}

///////////////// Get all users
###
GET http://localhost:4000/users HTTP/1.1

